trigger:
  branches:
    include:
      - main

variables:
  appName: 'my-flask-app-123'
  imageName: 'myflaskapp:v1'
  acrLoginServer: 'myacrboyan123.azurecr.io'
  resourceGroupName: 'devops-rg' 

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create \
        --resource-group $(resourceGroupName) \
        --template-file ../../../static-site-pipeline/devops-python-app/main.bicep \
        --parameters appName=$(appName) acrLoginServer=$(acrLoginServer) imageName=$(imageName)
    workingDirectory: '$(Build.SourcesDirectory)/devops-python-app/flask-app'
